name: Push docker image to ACR

# Deploy when change is made to main branch
on:
  push:
    branches:
      - main

# Jobs to execute
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      # Download source code into GitHub Actions runner (ubuntu-latest VM)
      - name: 'Checkout code'
        uses: actions/checkout@v4

      # Login via Azure CLI
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to DigitalOcean Container Registry
      - name: Login to DigitalOcean Container Registry
        run: echo "${{ secrets.DOCR_PASSWORD }}" | docker login ${{ secrets.DOCR_REGISTRY }} -u ${{ secrets.DOCR_USERNAME }} --password-stdin 

      # Build docker image
      - name: Build Image
        run:
          docker build . -t ${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPO }}:latest \
            --build-arg GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }} \
            --build-arg GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }} \
            --build-arg GMAIL_USER_EMAIL=${{ secrets.GMAIL_USER_EMAIL }} \
            --build-arg RECAPTCHA_PUBLIC_KEY=${{ secrets.RECAPTCHA_PUBLIC_KEY }} \
            --build-arg RECAPTCHA_PRIVATE_KEY=${{ secrets.RECAPTCHA_PRIVATE_KEY }} \
            --build-arg MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
            --build-arg MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
            --build-arg MS_TRANSLATOR_KEY=${{ secrets.MS_TRANSLATOR_KEY }} \
            --build-arg MS_BLOB_CONTAINER_NAME=${{ secrets.MS_BLOB_CONTAINER_NAME }} \
            --build-arg OPENAI_KEY=${{ secrets.OPENAI_KEY }} \
            --build-arg MS_BLOB_CONNECTION_STRING=${{ secrets.MS_BLOB_CONNECTION_STRING }}

      # Push Docker image to container repo (DOCR)
      - name: Push Image to DigitalOcean Container Registries
        run: docker push ${{ secrets.DOCR_REGISTRY }}/${{ secrets.DOCR_REPO }}:latest